package com.Exception;

public class Test1 {
    public static void main (String[] args) {
//        try {
//            int num = Integer.parseInt("XYZ");
//        } catch (NumberFormatException e) {
//            e.printStackTrace();
//        }

//        int[] arr = new int[5];
//        try {
//            int x = arr[10];
//        } catch (ArrayIndexOutOfBoundsException e) {
//            e.printStackTrace();
//        }

//        try {
//            FileInputStream file = new FileInputStream("non_existing_file.txt");
//        } catch (FileNotFoundException e) {
//            e.printStackTrace();
//        }

//        try {
//            FileInputStream file = new FileInputStream("non_existing_file.txt");
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
    }
}
